compressionLevel: mixed
enableGlobalCache: false
nodeLinker: pnp
yarnPath: .yarn/releases/yarn-4.6.0.cjs

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - darwin
    - linux
