compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

npmRegistryServer: "https://nexus.toss.bz/repository/npm-group/"

npmScopes:
  tossteam:
    npmAuthIdent: "${NEXUS_SHARED_IDENT:-}"
    npmPublishRegistry: "https://nexus-shared.toss.bz/repository/npm-shared/"
    npmRegistryServer: "https://nexus.toss.bz/repository/npm-group/"

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - darwin
    - linux

unsafeHttpWhitelist:
  - "*.toss.bz"
