labels: ["Suggest new strategy"]
body:
  - type: markdown
    attributes:
      value: |
        ## ✏️ Frontend Fundamentals 문서에 기여하기
        Frontend Fundamental 문서를 통해 알리고 싶은 좋은 코드의 기준과 패턴들을 제안해주세요.
        제안된 내용은 디스커션에서 충분히 논의된 후, 메인테이너의 최종 검토를 거쳐 문서에 반영돼요.

        만약 제안이 채택된다면, PR 작성을 부탁드릴 예정이에요.
        부담 없이 자유롭게 의견을 공유해 주시고, 함께 좋은 아이디어를 발전시켜 나가길 기대하고 있어요. 🚀

  - type: markdown
    attributes:
      value: |
        ## 패턴 제목
        - 제안하고자 하는 기준(또는 패턴)의 제목을 그대로 작성해 주세요. ex: 같이 실행되지 않는 코드 분리하기
        - "~하지 않기" 보다는 "~하기"로 제목을 작성해주세요.

  - type: textarea
    id: title
    attributes:
      label: 패턴 제목
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 문서 위계
        예시) 1. 가독성 > 맥락 줄이기 > D. 같이 실행되지 않는 코드 분리하기

  - type: textarea
    id: folder
    attributes:
      label: 문서 위계
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 개요
        해당 개선 아이디어를 제안하게 된 이유를 간단히 설명해 주세요.

  - type: textarea
    id: summary
    attributes:
      label: 개요
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 내용
        기존 문서 포맷에 맞춰서 작성해주세요.

  - type: textarea
    id: contents
    attributes:
      label: 내용
      value: |
        <!-- 해당 코드 패턴을 적용하기 이전에 어떤 어려움이 있었는지 서술해주시면 좋아요. -->
        {한줄설명}

        ## 📝 코드 예시
        <!-- 요구사항을 적어보거나, 유저 페르소나를 입혀서 작성해보면 입체적인 예시를 작성할 수 있어요 -->
        {예시코드 설명}

        ```tsx
        console.log("Bad code");
        ```

        ## 👃 코드 냄새 맡아보기
        <!-- 해당 코드의 문제점이나 개선이 필요한 이유를 구체적으로 작성해 주세요. --> 
        <!-- 4대 기준 중에 어떤 영역에 속하는지 함께 작성해주시면 좋아요 -->

        {냄새나는 이유}

        ## ✏️ 개선해보기
        <!-- 개선을 통해 얻게된 이점을 중심으로 작성해주세요. -->
        {개선 방법}
